name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: NPM
       uses: actions/setup-node@v4
       with:
         node-version: "20.x"
     - run: npm pack
     - name: Upload Artifact
       uses: actions/upload-artifact@v4
       with:
         name: ClearChatNK
         path: src/ClearChatNK-1.2.0.tgz